Purifiers get missing features, added ability to make class levels count towards other class levels for specific features only
Vek17/WrathMods-TabletopTweaks pull request #71
Opened 2021-09-18 03:43 UTC by pheonix99

TT Purifier technically doesn't lose those revelations, just has forced picks. The level 3 pick is unimplemented and probably unimplementable, so they shouldn't lose it.

They also get armor training as a fighter of four levels less from Celestial Armor, which should include advanced armor training.

Added both and component to enable the second one.

Haven't made armor training -> advanced armor training substitution for them yet.

2021-09-19 01:17 UTC, pheonix99 commented
Added crossclass scaling and support for Hellknight and Armored Battlemage armor training.

2021-09-19 04:58 UTC, Vek17 requested changes
Can you pull the latest master and rebase this, as well as run it through the linter based on the .editiorconfig on the project. Lots of noise so it is hard to see the actual changes.

2021-09-19 14:28 UTC, pheonix99 commented on TabletopTweaks/Bugfixes/Classes/Magus.cs
> +                Helpers.CreateBlueprint<BlueprintFeature>("ArmoredBattlemageArmorTrainingProgression", x =>
Sorry about that on the magus, will move the create blueprint methods over to Added Content as a whole.

Can't figure out how to rebase without making everything go super wierd - i have merged the latest master in.

Could you elaborate on the Linter? I think most of the noise is using Ctrl-K -> Ctrl-D to enforce the default formatting.

2021-09-19 15:51 UTC, pheonix99 commented on TabletopTweaks/Bugfixes/Classes/Magus.cs
> +                Helpers.CreateBlueprint<BlueprintFeature>("ArmoredBattlemageArmorTrainingProgression", x =>
Magus changes made, moved all the bp creates into the armor training file.

2021-09-20 16:04 UTC, pheonix99 commented on TabletopTweaks/Bugfixes/Classes/Magus.cs
> +                Helpers.CreateBlueprint<BlueprintFeature>("ArmoredBattlemageArmorTrainingProgression", x =>
Everything working now playtest is running fine.

2021-09-21 21:46 UTC, pheonix99 commented
@Vek17 Would it be easier for you to evaluate if I popped open a new branch from master and put the changes in there cleanly, without the mess I made trying to rebase and otherwise make things work?

2021-09-22 23:49 UTC, closed without merging